spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamerhub_db
    username: postgres
    password: P@ssw0rd

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080